name: learn-github-actions
on: 
    push: 
        branches: [main]
    
    pull_request:
        branches: [main]
        
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-node@v1
        with:
            python-version: 3.8
            
      - name: Install pytest
        run: pip install pytest
       
      - name: Install pytest
        run: pip install numpy
        
      
      - name: Test with pytest
        run: pytest
