name: Run tests
on: 
    push: 
        branches: [main]
    
    pull_request:
        branches: [main]
        
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-node@v1
        with:
            python-version: 3.8

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Test with pytest
        run: pytest
